# Database settings
# Overridden in production by environment variables
database:

  # the name of your JDBC driver
  driverClass: org.h2.Driver
  user: ignored
  password: ignored

  # the JDBC URL
  url: jdbc:h2:dev

# server settings
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

# Max number of requests to service per second
rateLimit: 100
